// GENERATED FILE — DO NOT EDIT. Run `npm run bundled-text:build`.
//
// Inlined from `MIT-license-tubesage.md`, which is the single source of truth.
// The licence and disclaimer the plugin makes the user accept before it will run.
// It is a legal instrument, so THIS CONSTANT is the file verbatim, in English:
// the generator neither reformats nor translates it, and the byte-for-byte gate
// proves it. What the modal does with it when rendering is the modal's business
// and is not claimed here. Gating the plugin behind a licence it then could not
// display at all was the worst of the three cases this generator fixes.
//
// It is inlined because Obsidian's community installer copies only `main.js`,
// `manifest.json` and `styles.css` into the plugin folder, so a modal that read
// this file at runtime found nothing on a store install. See
// `scripts/bundled-text-lib.mjs`; `scripts/bundled-text-packaging.test.mjs`
// fails if this constant and its source file differ by one byte.
export const LICENSE_TEXT = "# MIT License\n\nCopyright (c) [2024] [Richard McCorkle]\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\n# YouTube Content Usage Disclaimer\n\nThis software facilitates the extraction and summarization of publicly available YouTube video transcripts. Users of this software should be aware of the following:\n\n1. **Terms of Service Considerations**: The use of automated tools to extract content from YouTube may conflict with YouTube's Terms of Service. This software is provided for educational and personal use only.\n\n2. **Copyright Responsibility**: Users are solely responsible for ensuring their use of any extracted content complies with applicable copyright laws. The creators of this software do not endorse copyright infringement.\n\n3. **Fair Use Guidance**: When using extracted transcripts:\n   - Always include proper attribution to the original source\n   - Consider the purpose and nature of your use (personal research, education, etc.)\n   - Be mindful of the amount of content used\n   - Consider the potential effect on the market for the original content\n\n4. **Private Use Focus**: This tool is intended for private note-taking and personal knowledge management. Redistribution of extracted content may present additional legal considerations.\n\n5. **No Legal Warranty**: The creators of this software make no representations or warranties regarding the legality of any particular use case. Users should consult legal counsel for specific situations.\n\nBy using this software, you acknowledge your understanding of these considerations and agree to use the software responsibly.\n";
